stages:
  - lint
  - build
  - test

lint-rust:
  stage: lint
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add clippy rustfmt
  script:
    - cargo fmt -- --check
    - cargo clippy --all-targets -- -D clippy::all
    - cargo test

lint-python:
  stage: lint
  image: python:3.11
  script:
    - pip install poetry
    - poetry install
    - poetry run black visualize

build-rust:
  stage: build
  image: rust:latest
  services:
    - postgres:latest
  variables:
    DATABASE_URL: "postgres://postgres@postgres/quant_trader"
  before_script:
    - cargo install diesel_cli
  script:
    - diesel database reset
    - cargo build --release --verbose --jobs 1

test-rust:
  stage: test
  image: rust:latest
  before_script:
    - cargo install cargo-nextest
  script:
    - cargo nextest run --all
