stages:
  - lint
  - build

lint-rust:
  stage: lint
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add clippy rustfmt
    - cargo install diesel_cli
  script:
    - cargo fmt -- --check
    - cargo clippy --all-targets -- -D clippy::all
    - cargo test

lint-python:
  stage: lint
  image: python:3.11
  script:
    - pip install poetry
    - poetry install
    - poetry run black visualize

build-rust:
  when: manual
  stage: build
  image: rust:latest
  services:
    - postgres:latest
  variables:
    DATABASE_URL: "postgres://postgres@postgres/quant_trader"
  script:
    - diesel migration run
    - cargo build --release --verbose --jobs 1
