[package]
name = "btc_trader"
version = "0.1.0"
edition = "2021"
authors = ["Changfeng Lou<louchangfeng@outlook.com>"]


[[bin]]
bench = false
path = "crates/core/main.rs"
name = "btc_trader"

[workspace]
members = [
    "crates/binance_spot_connector_rust",
    "crates/binance_connector_rust_examples",
    "crates/test_binan_api",
]

[dependencies]
binance_spot_connector_rust = { path = "crates/binance_spot_connector_rust", features = [
    "full",
] }
test_binan_api = { path = "crates/test_binan_api" }
hyper = "0.14.25"
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
log = "0.4.17"
tokio = { version = "1.26.0", features = ["time", "full"] }
