version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: quant_trader
    environment:
      POSTGRES_DB: quant_trader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
