[package]
name = "quant_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
fern = { version = "0.6.2", features = ["colored"] }
log = "0.4.17"
