name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, fix-**, feat-**]
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  build-rs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64

      - name: Set up mold linker
        uses: rui314/setup-mold@v1

      - name: Setup Rust
        run: rustup install nightly

      - name: Install diesel
        run: cargo install diesel_cli --force --no-default-features --features postgres

      - name: Install postgresql
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql
          echo "host    all             all             127.0.0.1/32            md5" > sudo tee -a /etc/postgresql/10/main/pg_hba.conf
          sudo service postgresql restart && sleep 3
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
          sudo service postgresql restart && sleep 3
          echo "PG_DATABASE_URL=postgres://postgres:postgres@localhost/" >> $GITHUB_ENV
          echo "DATABASE_URL=postgres://postgres:postgres@localhost/rsquant" >> $GITHUB_ENV

      - name: Build
        run: |
          diesel database reset
          cargo build --release --verbose --jobs 1
