name: Build

on:
  push:
    branches: [master]
    tags:
      - "**"
  pull_request:
    branches: [master, dev, fix-**, feat-**]
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  build-rs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build image
        run: docker pull clux/muslrust:nightly

      - name: Lint
        run: docker run -v $PWD:/volume --rm -t clux/muslrust:nightly bash -c 'cargo build --release'

      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          echo "Tag : ${{  github.ref_name }}"
          cp $PWD/target/release/rsquant $PWD
          tar cvJf rsquant-${{  github.ref_name }}.tar.xz rsquant
          gh release create ${{ github.ref_name }} $PWD/rsquant.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
