name: Lint

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.0

  check-rs:
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy

      - name: Format
        run: cargo fmt -- --check

      - name: Lint
        run: cargo clippy --all-targets -- -D clippy::all

      - name: Test
        run: |
          cargo install cargo-nextest
          cargo test

  check-py:
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Format
        run: |
          pip install poetry
          poetry install
          poetry run black visualize
