name: Rust Main Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, rc-**]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fix Rust Version
        run: rustup install 1.65

      - name: Test
        run: cargo test

      - name: Lint Check
        run: cargo clippy --all-targets -- -D clippy::all
